---
# Data configurations --------------------------------------
json_filename: "filePaths.json"  # name of json file containing root file paths
dataset_name: "2024I_test"            # name of key within json containing dataset
has_scores: True                          # whether the files contain axo anomaly score branches
axo_version: "v4"                               # which axo version to use for score hists

# Coffea configurations  --------------------------------------
n_files: 1                                # number of files to process (-1 for all)
coffea_step_size: 200_000                 # step size for coffea processor
coffea_files_per_batch: 1                 # files per batch for coffea processor
coffea_max_chunks: 300000                 # maximum number of chunks to process
do_preprocessing: True                    # create a preprocessing json file 
visualize_task_graph: False               # save task graph as pdf (only use when processing 1 or 2 files)
save_hists: True                          # save histograms using pickle
save_branches: False                       # save branches to parquet file


# Object configurations ----------------------------------
# Which objects to process
objects: 
    l1:
    - "L1Jet"
    - "L1EG"
    - "L1Mu"
    scouting:
    - "ScoutingPFJet"
    - "ScoutingElectron"
    - "ScoutingMuonNoVtx"
    - "ScoutingMuonVtx"
    - "ScoutingPhoton"
    # full_reco: # only works on non-scouting datasets
    # - "Jet"
    # - "Electron"
    # - "Muon"

diobject_pairings: # Which invariant mass pairs to consider
    l1:
    - ["L1Jet","L1Jet"]
    - ["L1EG","L1EG"]
    - ["L1Mu","L1Mu"]
    scouting:
    - ["ScoutingPFJet","ScoutingPFJet"]
    - ["ScoutingElectron","ScoutingElectron"]
    - ["ScoutingMuonVtx","ScoutingMuonVtx"]
    #- ["ScoutingElectron", "ScoutingMuonVtx"]
    
# Histograms to make ---------------------------------------
histograms_1d:
    per_event: # histograms to make per event
    - "anomaly_score"
    - "ht"
    - "met"
    - "mult"
    - "pt"
    per_object_type: # histograms by object type, e.g. total L1 jet multiplicity & pT of all L1 jets in event
    - "ht"
    - "mult"
    - "pt"
    - "eta"
    - "phi"
    per_object: # histograms by object type, pt ordered, e.g. pT of leading and subleading jets
    - "pt"
    - "eta"
    - "phi"
    per_diobject_pair:
    - "mass"
    - "pt"
    - "eta"
    - "phi"
    
histograms_2d: # not implemented yet TODO: implement
    - ["anomaly_score","ht"]
    - ["anomaly_score","met"]
    - ["anomaly_score",["diobject","m"]]

objects_max_i:  # number of objects to plot for pt ordered object plotting
    "ScoutingPFJet" : 4
    "ScoutingElectron": 4
    "ScoutingMuonNoVtx": 4
    "ScoutingMuonVtx": 4
    "ScoutingPhoton": 4
    "L1Jet": 4
    "L1EG": 4
    "L1Mu": 4
    "Jet": 4
    "Electron": 4
    "Muon": 4

    
# Which triggers to save (comment out unwanted or add) -----------------------
triggers:
    # - 'all'
    # - 'DST_PFScouting_AXOVLoose'
    # - 'DST_PFScouting_AXOLoose' 
    - 'DST_PFScouting_AXONominal'
    # - 'DST_PFScouting_AXOTight'
    # - 'DST_PFScouting_AXOVTight'
    # - 'DST_PFScouting_CICADAVLoose'
    # - 'DST_PFScouting_CICADALoose'
    # - 'DST_PFScouting_CICADAMedium'
    # - 'DST_PFScouting_CICADATight'
    # - 'DST_PFScouting_CICADAVTight'
    # - 'DST_PFScouting_DoubleMuon'
    # - 'DST_PFScouting_JetHT'
    - 'DST_PFScouting_ZeroBias'

# List of branches to save to parquet file for fitting
# which branches to save (comment out unwanted)
branch_selection:
    "dimuon": 
        # - "dimuon_mass",                            # mass of dimuon pair
        # - "dimuon_pt",                              # pt of dimuon pair
        # - "dimuon_eta",                             # eta of dimuon pair
        # - "dimuon_phi",                             # phi of dimuon pair
        # - "dimuon_pt_1",                            # pt of first muon in dimuon pair
        # - "dimuon_pt_2",                            # pt of second muon in dimuon pair
        # - "dimuon_eta_1",                           # eta of first muon in dimuon pair
        # - "dimuon_eta_2",                           # eta of second muon in dimuon pair
        # - "dimuon_phi_1",                           # phi of first muon in dimuon pair
        # - "dimuon_phi_2",                           # phi of second muon in dimuon pair
    


# Object cleaning requirements -------------------------------------
object_cleaning:
    "ScoutingPFJet": # https://cms-hlt-scouting.docs.cern.ch/PathsRecoContent/EventContent/
        pt: 20.0 # GeV
        eta: 5
        phi:
    "ScoutingElectron": # 
        pt: 5.0 # GeV
        eta: 10 
    "ScoutingMuonNoVtx": # 
        pt: 3.0 # GeV
        eta: 10
    "ScoutingMuonVtx": # 
        pt: 3.0 # GeV 
        eta: 10
    "ScoutingPhoton": # 
        pt: 5.0 # GeV
        eta: 10
    "L1Jet": # https://twiki.cern.ch/twiki/bin/view/CMSPublic/L1TJetsEtSum2023
        pt: 0.1 # GeV
        eta: 5.0
    "L1EGamma": # https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/EgTau2023Performance
        pt: 0.1 # GeV
        eta: 2.5
    "L1Mu":
        pt: 0.1 # GeV
        eta: 2.4 # https://twiki.cern.ch/twiki/bin/view/CMSPublic/Level1MuonTriggerPerformance2023
    "Jet":
        pt: 30.0 # GeV
        eta: 10
    "Muon":
        pt: 3.0 # GeV
        eta: 10 
    "Electron":
        pt: 5.0 # GeV
        eta: 10 

# Modules to run -------------------------------------------
modules:
    - "default"
    - "efficiency"
    - "purity"
    - "pileup"

# # Object labeling dictionary -------------------------------------------
# object_label:
#     "ScoutingPFJet": "j"
#     "ScoutingElectron": "e"
#     "ScoutingMuonNoVtx": ""\mu""
#     "ScoutingMuonVtx": ""\mu"" 
#     "ScoutingPhoton": ""\gamma""
#     "L1Jet": "j"
#     "L1EGamma": "EG"
#     "L1Mu": ""L1\mu""

# AXOL1TL Thresholds -------------------------------------------
axo_thresholds:
- version: "v3"
  path: "config/axo_thresholds_v3.csv"
- version: "v4"
  path: "config/axo_thresholds_v4.csv"




