---
# Data configurations --------------------------------------
json_filename: "filePaths.json"  # name of json file containing root file paths
dataset_name: "2024I_test"            # name of key within json containing dataset
has_scores: True                          # whether the files contain axo anomaly score branches
is_scouting: True                         # whether the files are scouting nanos
axo_v: "v4"                               # which axo version to use for score hists

# Coffea configurations  --------------------------------------
n_files: 1                                # number of files to process (-1 for all)
coffea_step_size: 200_000                 # step size for coffea processor
coffea_files_per_batch: 1                 # files per batch for coffea processor
coffea_max_chunks: 300000                 # maximum number of chunks to process
visualize_task_graph: False                        # save task graph as pdf (only use when processing 1 or 2 files)
save_hists: True                        # save histograms using pickle
do_preprocess: True                    # create a preprocessing json file 

# Object configurations ----------------------------------
# Which objects to process
objects: 
    # Scouting objects
    - "ScoutingPFJet"
    - "ScoutingElectron"
    - "ScoutingMuonNoVtx"
    - "ScoutingMuonVtx"
    - "ScoutingPhoton"
    # L1 objects 
    - "L1Jet"
    - "L1EGamma"
    - "L1Mu"
    # Full Reco objects
    # - "Jet"
    # - "Electron"
    # - "Muon"
 

# Which triggers to save (comment out unwanted or add) -----------------------
triggers:
    # - 'DST_PFScouting_AXOLoose' 
    - 'DST_PFScouting_AXONominal'
    # - 'DST_PFScouting_AXOTight'
    # - 'DST_PFScouting_AXOVLoose'
    # - 'DST_PFScouting_AXOVTight'
    # - 'DST_PFScouting_CICADALoose'
    # - 'DST_PFScouting_CICADAMedium'
    # - 'DST_PFScouting_CICADATight'
    # - 'DST_PFScouting_CICADAVLoose'
    # - 'DST_PFScouting_CICADAVTight'
    # - 'DST_PFScouting_DoubleMuon'
    # - 'DST_PFScouting_JetHT'
    # - 'DST_PFScouting_ZeroBias'

# Object cleaning requirements -------------------------------------
object_cleaning:
    "ScoutingPFJet": # https://cms-hlt-scouting.docs.cern.ch/PathsRecoContent/EventContent/
        pt: 20.0 # GeV
        eta: 5
    "ScoutingElectron": # 
        pt: 5.0 # GeV
        eta: 10 
    "ScoutingMuonNoVtx": # 
        pt: 3.0 # GeV
        eta: 10
    "ScoutingMuonVtx": # 
        pt: 3.0 # GeV 
        eta: 10
    "ScoutingPhoton": # 
        pt: 5.0 # GeV
        eta: 10
    "L1Jet": # https://twiki.cern.ch/twiki/bin/view/CMSPublic/L1TJetsEtSum2023
        pt: 0.1 # GeV
        eta: 5.0
    "L1EGamma": # https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/EgTau2023Performance
        pt: 0.1 # GeV
        eta: 2.5
    "L1Mu":
        pt: 0.1 # GeV
        eta: 2.4 # https://twiki.cern.ch/twiki/bin/view/CMSPublic/Level1MuonTriggerPerformance2023
    "Jet":
        pt: 30.0 # GeV
        eta: 10
    "Muon":
        pt: 3.0 # GeV
        eta: 10 
    "Electron":
        pt: 5.0 # GeV
        eta: 10 

# # Object labeling dictionary -------------------------------------------
# object_label:
#     "ScoutingPFJet": "j"
#     "ScoutingElectron": "e"
#     "ScoutingMuonNoVtx": ""\mu""
#     "ScoutingMuonVtx": ""\mu"" 
#     "ScoutingPhoton": ""\gamma""
#     "L1Jet": "j"
#     "L1EGamma": "EG"
#     "L1Mu": ""L1\mu""

# AXOL1TL Thresholds -------------------------------------------
axo_thresholds:
    v3:
        'AXOVTight'  : 25000/16
        'AXOTight'   : 20486/16
        'AXONominal' : 18580/16
        'AXOLoose'   : 17596/16
        'AXOVLoose'  : 15717/16
    v4:
    v5:


